backend:
  name: github
  repo: procload/rcm # Path to your Github repository
  branch: master # Branch to update (master by default)

media_folder: "source/images" # Folder where user uploaded files should go
public_folder: "source" # CMS now knows 'source' is the public folder and will strip this from the path

publish_mode: editorial_workflow

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "source" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}/{{month}}/{{day}}/{{slug}}"
    extension: "html.markdown"
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Tags", name: "tags", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
